# Generated by Django 3.1.2 on 2020-12-16 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_db_step_public_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_step',
            name='api_body_method',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
