# Generated by Django 3.1.2 on 2020-12-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_auto_20201216_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_cases',
            name='name',
            field=models.CharField(default='', max_length=50, null=True, verbose_name='用例名字'),
        ),
    ]
