# Generated by Django 3.1.2 on 2021-01-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0018_db_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_login',
            name='body_method',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='db_project_header',
            name='key',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
