# Generated by Django 3.1.2 on 2021-01-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0019_auto_20210125_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_step',
            name='api_login',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
