# Generated by Django 3.1.2 on 2021-08-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0020_db_step_api_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_global_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('user_id', models.CharField(max_length=10, null=True)),
                ('data', models.TextField(null=True)),
            ],
        ),
    ]
